apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastify-widget-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastify-widget-backend
  template:
    metadata:
      labels:
        app: fastify-widget-backend
    spec:
      containers:
        - name: fastify-widget-backend
          # Use the full ECR image URI with the latest tag
          image: 813300926344.dkr.ecr.ap-south-1.amazonaws.com/fastify-widget-backend:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres  # Ensure this matches your PostgreSQL service name
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: usdt_widget
            - name: DB_PASSWORD
              value: usdt123
            - name: DB_NAME
              value: usdt_widget
---
apiVersion: v1
kind: Service
metadata:
  name: fastify-widget-backend
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: fastify-widget-backend
