version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=usdt_widget
      - DB_USERNAME=usdt_widget
      - DB_SECRET=usdt123
      - JWT_SECRET=3wzxmoDsmQteZ3LKLndsJRDKVjHKgzHRQbfjTeugLzyvSaQDfN2q2qJjcackKPTgd279bu2zMCx3VbRbvS9vpF5AJjG4YqZxw3ukWqr5zX9hZo
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=usdt_widget
      - POSTGRES_PASSWORD=usdt123
      - POSTGRES_DB=usdt_widget
    ports:
      - "5432:5432"
