apiVersion: autoscaling/v2  # Change to autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastify-widget-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastify-widget-backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
